---
name: Setup Nix
description: Install Nix with flakes enabled
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v16
      with:
        extra-conf: |
          accept-flake-config = true
          experimental-features = nix-command flakes recursive-nix
